### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by mbuchholz81** [tildeclub/tilde.club#94] opened 2019-09-18 05:54 UTC
a real code of conduct is definitely a must.  Looking for input on things to have and not to have. :)

**Comment by audiodude** [comment] 2019-09-18 05:58
The easy route here is to just copy paste someone else's CoC and be done with it. The easier route is some kind of simple one off "there is one rule: don't be a jerk" or "respect one another".

However, I think the key to a good code of conduct is that it 1) has community buy in and 2) has distinct and specific descriptions of how violations will be handled, and how accusations of violations can be appealed.

When things go wrong, generally BOTH sides of a confrontation will start screaming CODE OF CONDUCT! That's the point at which either the issue is dealt with consistently with the written code and precedent, or the community falls apart.

**Comment by coreyreichle** [comment] 2019-09-18 11:49
Members of the tildeverse seem to be centering around the tilde.town's code of conduct, or something very similarly worded:

https://tilde.town/wiki/conduct.html
https://tilde.wiki/?page=code-of-conduct
https://www.thunix.net/tos
https://aussies.space/coc.php
https://yourtilde.com/conduct/
https://tilde.institute/coc

Seems the pertinent chuck is:

> Participate in an authentic and active way. In doing so, you contribute to the health and longevity of tilde.town.
> Exercise consideration and respect in your speech and actions.
> Attempt collaboration before conflict.
> Refrain from demeaning, discriminatory, or harassing behavior and speech.
> If anyone asks you to stop a particular kind of behavior, always err on the side of respecting their wishes. If you believe their request is unreasonable or unfair, ask an admin, but don't respond with hostility.
> Be mindful of your surroundings and of your fellow participants. Alert community leaders if you notice a dangerous situation, someone in distress, or violations of this code of conduct, even if they seem inconsequential.

**Comment by benharri** [comment] 2019-09-18 18:12
[Related ML thread](https://lists.tildeverse.org/hyperkitty/list/tildeclub@lists.tildeverse.org/thread/DSDHKNPNFXQECNPJ57T6W5GYKLGCFTPD/)

**Comment by Mikaela** [comment] 2019-09-19 12:28
I think the most popular ones [due to GitHub support](https://help.github.com/en/articles/adding-a-code-of-conduct-to-your-project) are:

* https://www.contributor-covenant.org/
* http://citizencodeofconduct.org/

**Comment by benharri** [comment] 2019-09-19 22:10
[PR](https://github.com/tildeclub/site/pull/3) and [draft](http://tilde.club/~benharri/coc.html) pushed.

**Comment by benharri** [comment] 2019-09-20 12:59
Closed by [site#3](https://github.com/tildeclub/site/pull/3).

**Closed by benharri** 2019-09-20 12:59 UTC
